services:
  - type: web
    name: docentes-ficct
    env: php
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force || true
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://docentes-ficct.onrender.com

